# Generated by Django 5.0.1 on 2024-01-03 10:51

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cate_name', models.CharField(help_text='Specify a cultural category', max_length=50, verbose_name='cate name')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Cate',
            },
        ),
        migrations.CreateModel(
            name='Cit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('point_geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
            options={
                'verbose_name_plural': 'Cits',
            },
        ),
        migrations.CreateModel(
            name='Pla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pla_name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='pla_images/')),
                ('active', models.BooleanField(default=True)),
                ('point_geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.cate')),
            ],
            options={
                'verbose_name_plural': 'Plas',
            },
        ),
    ]
