# Generated by Django 5.0.1 on 2024-01-03 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pla',
            name='categories',
        ),
        migrations.DeleteModel(
            name='Cit',
        ),
        migrations.DeleteModel(
            name='Cate',
        ),
        migrations.DeleteModel(
            name='Pla',
        ),
    ]
