# Generated by Django 5.0.1 on 2024-01-04 03:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='places',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='backend.place'),
        ),
    ]
