# Generated by Django 5.0.1 on 2024-01-04 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_location_places'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='places',
        ),
    ]
